//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUMUONPHONG
    {
        public Nullable<int> IDDocGia { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public System.DateTime ThoiGianMuon { get; set; }
        public System.DateTime ThoiGianTra { get; set; }
        public int ID { get; set; }
        public string delete_flag { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
