

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLiThuVien.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class QuanLyThuVienEntities : DbContext
{
    public QuanLyThuVienEntities()
        : base("name=QuanLyThuVienEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<BANPHAT> BANPHATs { get; set; }

    public virtual DbSet<CHUDE> CHUDEs { get; set; }

    public virtual DbSet<DOCGIA> DOCGIAs { get; set; }

    public virtual DbSet<LICHSUMUONPHONG> LICHSUMUONPHONGs { get; set; }

    public virtual DbSet<LOPTAPHUAN> LOPTAPHUANs { get; set; }

    public virtual DbSet<NGUOIDANGKY> NGUOIDANGKies { get; set; }

    public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }

    public virtual DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }

    public virtual DbSet<NHOMSACH> NHOMSACHes { get; set; }

    public virtual DbSet<PHONG> PHONGs { get; set; }

    public virtual DbSet<SACH> SACHes { get; set; }

    public virtual DbSet<TACGIA> TACGIAs { get; set; }

    public virtual DbSet<THONGTINMUONTRA> THONGTINMUONTRAs { get; set; }

    public virtual DbSet<THUGOPY> THUGOPies { get; set; }

    public virtual DbSet<USER> USERs { get; set; }

    public virtual DbSet<VITRI> VITRIs { get; set; }

    public virtual DbSet<VIEW_BORROWERS> VIEW_BORROWERS { get; set; }

    public virtual DbSet<Temp> Temps { get; set; }


    public virtual ObjectResult<proc_layDSMuonTra_Result> proc_layDSMuonTra(string maDocGia, Nullable<int> dieukien)
    {

        var maDocGiaParameter = maDocGia != null ?
            new ObjectParameter("maDocGia", maDocGia) :
            new ObjectParameter("maDocGia", typeof(string));


        var dieukienParameter = dieukien.HasValue ?
            new ObjectParameter("dieukien", dieukien) :
            new ObjectParameter("dieukien", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_layDSMuonTra_Result>("proc_layDSMuonTra", maDocGiaParameter, dieukienParameter);
    }


    public virtual ObjectResult<proc_layTTMuonSach_Result> proc_layTTMuonSach(string maSach)
    {

        var maSachParameter = maSach != null ?
            new ObjectParameter("maSach", maSach) :
            new ObjectParameter("maSach", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_layTTMuonSach_Result>("proc_layTTMuonSach", maSachParameter);
    }

}

}

