//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThuVienEntities : DbContext
    {
        public QuanLyThuVienEntities()
            : base("name=QuanLyThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANPHAT> BANPHATs { get; set; }
        public DbSet<CHUDE> CHUDEs { get; set; }
        public DbSet<DOCGIA> DOCGIAs { get; set; }
        public DbSet<LICHSUMUONPHONG> LICHSUMUONPHONGs { get; set; }
        public DbSet<LOPTAPHUAN> LOPTAPHUANs { get; set; }
        public DbSet<NGUOIDANGKY> NGUOIDANGKies { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }
        public DbSet<NHOMSACH> NHOMSACHes { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<SACH> SACHes { get; set; }
        public DbSet<TACGIA> TACGIAs { get; set; }
        public DbSet<THONGTINMUONTRA> THONGTINMUONTRAs { get; set; }
        public DbSet<THUGOPY> THUGOPies { get; set; }
        public DbSet<VITRI> VITRIs { get; set; }
        public DbSet<VIEW_BORROWERS> VIEW_BORROWERS { get; set; }
    }
}
