//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.THONGTINMUONTRAs = new HashSet<THONGTINMUONTRA>();
            this.THONGTINMUONTRAs1 = new HashSet<THONGTINMUONTRA>();
            this.USERs = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        public string TenNhanVien { get; set; }
        public string ChucVu { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<THONGTINMUONTRA> THONGTINMUONTRAs { get; set; }
        public virtual ICollection<THONGTINMUONTRA> THONGTINMUONTRAs1 { get; set; }
        public virtual ICollection<USER> USERs { get; set; }
    }
}
