
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLiThuVien.Models
{

using System;
    using System.Collections.Generic;
    
public partial class USER
{

    public int ID { get; set; }

    public int USERNAME { get; set; }

    public string PASSWORD { get; set; }

    public string PASSWORD_SALT { get; set; }

    public string ROLE { get; set; }



    public virtual DOCGIA DOCGIA { get; set; }

    public virtual NHANVIEN NHANVIEN { get; set; }

}

}
